# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HSV-Moder.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 730)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 260, 271, 364))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_h = QtWidgets.QHBoxLayout()
        self.horizontalLayout_h.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_h.setSpacing(10)
        self.horizontalLayout_h.setObjectName("horizontalLayout_h")
        self.label_h = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_h.setObjectName("label_h")
        self.horizontalLayout_h.addWidget(self.label_h)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.hSliderT = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.hSliderT.setMaximum(255)
        self.hSliderT.setOrientation(QtCore.Qt.Horizontal)
        self.hSliderT.setObjectName("hSliderT")
        self.horizontalLayout_4.addWidget(self.hSliderT)
        self.hSliderTValue = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.hSliderTValue.setObjectName("hSliderTValue")
        self.horizontalLayout_4.addWidget(self.hSliderTValue)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hSliderB = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.hSliderB.setMaximum(255)
        self.hSliderB.setOrientation(QtCore.Qt.Horizontal)
        self.hSliderB.setObjectName("hSliderB")
        self.horizontalLayout.addWidget(self.hSliderB)
        self.hSliderBValue = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.hSliderBValue.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.hSliderBValue.setObjectName("hSliderBValue")
        self.horizontalLayout.addWidget(self.hSliderBValue)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_h.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_h)
        self.horizontalLayout_s = QtWidgets.QHBoxLayout()
        self.horizontalLayout_s.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_s.setSpacing(10)
        self.horizontalLayout_s.setObjectName("horizontalLayout_s")
        self.label_s = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_s.setObjectName("label_s")
        self.horizontalLayout_s.addWidget(self.label_s)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sSliderT = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.sSliderT.setMinimumSize(QtCore.QSize(0, 0))
        self.sSliderT.setMaximum(255)
        self.sSliderT.setOrientation(QtCore.Qt.Horizontal)
        self.sSliderT.setObjectName("sSliderT")
        self.horizontalLayout_5.addWidget(self.sSliderT)
        self.sSliderTValue = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sSliderTValue.setObjectName("sSliderTValue")
        self.horizontalLayout_5.addWidget(self.sSliderTValue)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sSliderB = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.sSliderB.setMaximum(255)
        self.sSliderB.setOrientation(QtCore.Qt.Horizontal)
        self.sSliderB.setObjectName("sSliderB")
        self.horizontalLayout_6.addWidget(self.sSliderB)
        self.sSliderBValue = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sSliderBValue.setObjectName("sSliderBValue")
        self.horizontalLayout_6.addWidget(self.sSliderBValue)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_s.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_s)
        self.horizontalLayout_v = QtWidgets.QHBoxLayout()
        self.horizontalLayout_v.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_v.setSpacing(10)
        self.horizontalLayout_v.setObjectName("horizontalLayout_v")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_v.addWidget(self.label_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.vSliderT = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.vSliderT.setMaximum(255)
        self.vSliderT.setOrientation(QtCore.Qt.Horizontal)
        self.vSliderT.setObjectName("vSliderT")
        self.horizontalLayout_7.addWidget(self.vSliderT)
        self.vSliderTValue = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.vSliderTValue.setObjectName("vSliderTValue")
        self.horizontalLayout_7.addWidget(self.vSliderTValue)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.vSliderB = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.vSliderB.setMaximum(255)
        self.vSliderB.setOrientation(QtCore.Qt.Horizontal)
        self.vSliderB.setObjectName("vSliderB")
        self.horizontalLayout_8.addWidget(self.vSliderB)
        self.vSliderBValue = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.vSliderBValue.setObjectName("vSliderBValue")
        self.horizontalLayout_8.addWidget(self.vSliderBValue)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_v.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_v)
        self.pic = QtWidgets.QLabel(self.centralwidget)
        self.pic.setGeometry(QtCore.QRect(290, 60, 640, 480))
        self.pic.setObjectName("pic")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 271, 136))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.filePath = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.filePath.setMaximumSize(QtCore.QSize(800, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.filePath.setFont(font)
        self.filePath.setAutoFillBackground(False)
        self.filePath.setObjectName("filePath")
        self.verticalLayout_2.addWidget(self.filePath)
        self.picLoad = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.picLoad.setMaximumSize(QtCore.QSize(16777215, 40))
        self.picLoad.setObjectName("picLoad")
        self.verticalLayout_2.addWidget(self.picLoad)
        self.bBack = QtWidgets.QPushButton(self.centralwidget)
        self.bBack.setGeometry(QtCore.QRect(450, 570, 99, 27))
        self.bBack.setObjectName("bBack")
        self.bNext = QtWidgets.QPushButton(self.centralwidget)
        self.bNext.setGeometry(QtCore.QRect(690, 570, 99, 27))
        self.bNext.setObjectName("bNext")
        self.lSelector = QtWidgets.QLabel(self.centralwidget)
        self.lSelector.setGeometry(QtCore.QRect(580, 570, 67, 21))
        self.lSelector.setAlignment(QtCore.Qt.AlignCenter)
        self.lSelector.setObjectName("lSelector")
        self.cErosion = QtWidgets.QCheckBox(self.centralwidget)
        self.cErosion.setGeometry(QtCore.QRect(10, 190, 97, 22))
        self.cErosion.setObjectName("cErosion")
        self.cDilate = QtWidgets.QCheckBox(self.centralwidget)
        self.cDilate.setGeometry(QtCore.QRect(130, 190, 97, 22))
        self.cDilate.setObjectName("cDilate")
        self.cModulation = QtWidgets.QCheckBox(self.centralwidget)
        self.cModulation.setGeometry(QtCore.QRect(10, 230, 97, 22))
        self.cModulation.setObjectName("cModulation")
        self.verticalLayoutWidget.raise_()
        self.pic.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.bBack.raise_()
        self.bNext.raise_()
        self.lSelector.raise_()
        self.cErosion.raise_()
        self.cDilate.raise_()
        self.cModulation.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_h.setText(_translate("MainWindow", "H"))
        self.hSliderTValue.setText(_translate("MainWindow", "0"))
        self.hSliderBValue.setText(_translate("MainWindow", "0"))
        self.label_s.setText(_translate("MainWindow", "S"))
        self.sSliderTValue.setText(_translate("MainWindow", "0"))
        self.sSliderBValue.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "V"))
        self.vSliderTValue.setText(_translate("MainWindow", "0"))
        self.vSliderBValue.setText(_translate("MainWindow", "0"))
        self.pic.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Archivo"))
        self.filePath.setPlaceholderText(_translate("MainWindow", "Ruta de archivo"))
        self.picLoad.setText(_translate("MainWindow", "Cargar"))
        self.bBack.setText(_translate("MainWindow", "Back"))
        self.bNext.setText(_translate("MainWindow", "Next"))
        self.lSelector.setText(_translate("MainWindow", "0"))
        self.cErosion.setText(_translate("MainWindow", "Erosion"))
        self.cDilate.setText(_translate("MainWindow", "Dilate"))
        self.cModulation.setText(_translate("MainWindow", "Modulation"))

